import { TestBed } from '@angular/core/testing';
import { provideHttpClient } from '@angular/common/http';
import { provideHttpClientTesting, HttpTestingController } from '@angular/common/http/testing';
import { throwError } from 'rxjs';
import { AuthService } from './auth.service';
import { environment } from '../../../environments/environment';

describe('AuthService', () => {
    let service: AuthService;
    let httpMock: HttpTestingController;

    beforeEach(() => {
        TestBed.configureTestingModule({
            providers: [provideHttpClient(), provideHttpClientTesting(), AuthService]
        });
        service = TestBed.inject(AuthService);
        httpMock = TestBed.inject(HttpTestingController);
    });

    afterEach(() => {
        httpMock.verify();
    });

    it('should be created', () => {
        expect(service).toBeTruthy();
    });

    it('should POST /auth/login with credentials and withCredentials: true', async () => {
        const credentials = { email: 'admin@example.com', password: 'password123' };
        const mockResponse = {
            success: true,
            data: {
                accessToken: 'jwt.token.here',
                refreshToken: 'refresh.token.here',
                user: { id: 'usr-1', email: 'admin@example.com', role: 'admin' }
            },
            message: 'Login successful'
        };

        const loginPromise = service.login(credentials);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        expect(req.request.method).toBe('POST');
        expect(req.request.withCredentials).toBe(true);
        expect(req.request.body).toEqual(credentials);
        req.flush(mockResponse);

        const res = await loginPromise;
        expect(res.success).toBe(true);
        expect(res.data?.accessToken).toBe('jwt.token.here');
        expect(res.data?.user?.email).toBe('admin@example.com');
    });

    it('should handle login error gracefully', async () => {
        const credentials = { email: 'wrong@example.com', password: 'bad' };

        const loginPromise = service.login(credentials);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        req.flush(
            { error: { code: 'UNAUTHORIZED', message: 'Invalid email or password' } },
            { status: 401, statusText: 'Unauthorized' }
        );

        const res = await loginPromise;
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('UNAUTHORIZED');
        expect(res.error?.message).toContain('Invalid email or password');
    });

    it('should handle login error when err.error.error is defined', async () => {
        const credentials = { email: 'wrong@example.com', password: 'bad' };
        const loginPromise = service.login(credentials);
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        req.flush({ error: { code: 'CUSTOM_ERR', message: 'Nested error' } }, { status: 400, statusText: 'Bad Request' });
        const res = await loginPromise;
        expect(res.error?.code).toBe('CUSTOM_ERR');
        expect(res.error?.message).toBe('Nested error');
    });

    it('should fallback to default error string in login when error payload is empty', async () => {
        const loginPromise = service.login({ email: 'x', password: 'y' });
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        // We simulate a raw ErrorEvent where err.error is a ProgressEvent or empty object without code/message
        req.error(new ProgressEvent('error'), { status: 0, statusText: 'Unknown Error' });
        const res = await loginPromise;
        expect(res.error?.code).toBe('UNAUTHORIZED');
        expect(res.error?.message).toBe(`Http failure response for ${environment.apiUrl}/auth/login: 0 Unknown Error`);
    });

    it('should completely fallback in login when error payload is an empty object without message', async () => {
        const loginPromise = service.login({ email: 'x', password: 'y' });
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        req.flush({}, { status: 500, statusText: 'Server Error' });
        const res = await loginPromise;
        // In this case, err.error is {}, err.message is generated by HttpClient
        expect(res.error?.code).toBe('UNAUTHORIZED');
        // HttpClient constructs a message when it parses JSON but status is 500.
        // We ensure we don't crash and get some string back.
        expect(res.error?.message).toContain('Http failure response');
    });

    it('should handle login error when err.error is null', async () => {
        const loginPromise = service.login({ email: 'x', password: 'y' });
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/login`);
        req.flush(null, { status: 500, statusText: 'Server Error' });
        const res = await loginPromise;
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('UNAUTHORIZED');
    });

    it('should POST /auth/register with payload and withCredentials: true', async () => {
        const payload = { email: 'new@example.com', password: 'password123', name: 'New User', role: 'user' };
        const mockResponse = {
            success: true,
            data: { user: { id: 'usr-2', email: 'new@example.com', name: 'New User', role: 'user' } },
            message: 'User registered successfully'
        };

        const registerPromise = service.register(payload);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/register`);
        expect(req.request.method).toBe('POST');
        expect(req.request.withCredentials).toBe(true);
        expect(req.request.body).toEqual(payload);
        req.flush(mockResponse);

        const res = await registerPromise;
        expect(res.success).toBe(true);
        expect(res.data?.user?.email).toBe('new@example.com');
    });

    it('should handle register error gracefully', async () => {
        const payload = { email: 'existing@example.com', password: 'password123', name: 'Existing' };

        const registerPromise = service.register(payload);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/register`);
        req.flush(
            { error: { code: 'CONFLICT', message: 'User already exists' } },
            { status: 409, statusText: 'Conflict' }
        );

        const res = await registerPromise;
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('CONFLICT');
    });

    it('should handle register error when err.error.error is defined', async () => {
        const registerPromise = service.register({ email: 'x', password: 'y', name: 'z' });
        httpMock.expectOne(`${environment.apiUrl}/auth/register`).flush(
            { error: { code: 'DEEP_REG', message: 'Deep register error' } },
            { status: 400, statusText: 'Bad Request' }
        );
        const res = await registerPromise;
        expect(res.error?.code).toBe('DEEP_REG');
        expect(res.error?.message).toBe('Deep register error');
    });

    it('should fallback to default error string in register when error payload is empty', async () => {
        const registerPromise = service.register({ email: 'x', password: 'y', name: 'z' });
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/register`);
        req.error(new ProgressEvent('error'));
        const res = await registerPromise;
        expect(res.error?.code).toBe('REGISTRATION_ERROR');
        expect(res.error?.message).toContain('Http failure response');
    });

    it('should POST /auth/refresh with withCredentials: true', async () => {
        const mockResponse = {
            success: true,
            data: { accessToken: 'new.jwt.token', refreshToken: 'new.refresh.token' },
            message: 'Token refreshed successfully'
        };

        const refreshPromise = service.refresh();

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/refresh`);
        expect(req.request.method).toBe('POST');
        expect(req.request.withCredentials).toBe(true);
        req.flush(mockResponse);

        const res = await refreshPromise;
        expect(res.success).toBe(true);
        expect(res.data?.accessToken).toBe('new.jwt.token');
    });

    it('should POST /auth/refresh with payload when provided', async () => {
        const payload = { refreshToken: 'dummy-token' };
        const refreshPromise = service.refresh(payload);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/refresh`);
        expect(req.request.method).toBe('POST');
        expect(req.request.body).toEqual(payload);
        req.flush({ success: true, data: { accessToken: 'new-token' } });

        const res = await refreshPromise;
        expect(res.success).toBe(true);
    });

    it('should pass empty object or handle undefined payload in refresh', async () => {
        const refreshPromise = service.refresh(undefined);

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/refresh`);
        expect(req.request.method).toBe('POST');
        expect(req.request.body).toEqual({});
        req.flush({ success: true, data: { accessToken: 'new-token' } });

        const res = await refreshPromise;
        expect(res.success).toBe(true);
    });

    it('should handle refresh error gracefully', async () => {
        const refreshPromise = service.refresh();

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/refresh`);
        req.flush(
            { error: { code: 'UNAUTHORIZED', message: 'Invalid refresh token' } },
            { status: 401, statusText: 'Unauthorized' }
        );

        const res = await refreshPromise;
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('UNAUTHORIZED');
    });

    it('should handle refresh error when err.error.error is defined', async () => {
        const refreshPromise = service.refresh();
        httpMock.expectOne(`${environment.apiUrl}/auth/refresh`).flush(
            { error: { code: 'DEEP_REF', message: 'Deep refresh error' } },
            { status: 400, statusText: 'Bad Request' }
        );
        const res = await refreshPromise;
        expect(res.error?.code).toBe('DEEP_REF');
        expect(res.error?.message).toBe('Deep refresh error');
    });

    it('should fallback to default error string in refresh when error payload is empty', async () => {
        const refreshPromise = service.refresh();
        const req = httpMock.expectOne(`${environment.apiUrl}/auth/refresh`);
        req.error(new ProgressEvent('error'));
        const res = await refreshPromise;
        expect(res.error?.code).toBe('REFRESH_ERROR');
        expect(res.error?.message).toContain('Http failure response');
    });

    it('should POST /auth/logout with withCredentials: true', async () => {
        const mockResponse = {
            success: true,
            message: 'Logged out successfully'
        };

        const logoutPromise = service.logout();

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/logout`);
        expect(req.request.method).toBe('POST');
        expect(req.request.withCredentials).toBe(true);
        req.flush(mockResponse);

        const res = await logoutPromise;
        expect(res.success).toBe(true);
    });

    it('should handle logout error gracefully', async () => {
        const logoutPromise = service.logout();

        const req = httpMock.expectOne(`${environment.apiUrl}/auth/logout`);
        req.error(new ProgressEvent('error'), { status: 500, statusText: 'Internal Server Error' });

        const res = await logoutPromise;
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('LOGOUT_ERROR');
    });

    it('should fallback to hardcoded default message in login when err has no message', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({})));
        const res = await service.login({ email: 'x', password: 'y' });
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('UNAUTHORIZED');
        expect(res.error?.message).toBe('Login failed. Please check your credentials.');
    });

    it('should fallback to hardcoded default message in register when err has no message', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({})));
        const res = await service.register({ email: 'x', password: 'y', name: 'z' });
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('REGISTRATION_ERROR');
        expect(res.error?.message).toBe('Registration failed.');
    });

    it('should fallback to hardcoded default message in refresh when err has no message', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({})));
        const res = await service.refresh();
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('REFRESH_ERROR');
        expect(res.error?.message).toBe('Token refresh failed.');
    });

    it('should fallback to hardcoded default message in logout when err has no message', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({})));
        const res = await service.logout();
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('LOGOUT_ERROR');
        expect(res.error?.message).toBe('Logout failed.');
    });

    it('should use err.message in logout when present', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => new Error('Custom logout failure')));
        const res = await service.logout();
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('LOGOUT_ERROR');
        expect(res.error?.message).toBe('Custom logout failure');
    });

    it('should handle register error when err.error is null', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({ error: null })));
        const res = await service.register({ email: 'x', password: 'y', name: 'z' });
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('REGISTRATION_ERROR');
        expect(res.error?.message).toBe('Registration failed.');
    });

    it('should handle refresh error when err.error is null', async () => {
        vi.spyOn((service as any).http, 'post').mockReturnValue(throwError(() => ({ error: null })));
        const res = await service.refresh();
        expect(res.success).toBe(false);
        expect(res.error?.code).toBe('REFRESH_ERROR');
        expect(res.error?.message).toBe('Token refresh failed.');
    });
});
